language: python
before_install:
 - chmod +x ./flaskapp/st.sh
install:
 - pip3 install flask
 - pip3 install matplotlib.pyplot
 - pip3 install numpy
 - pip3 install pillow
 - pip3 install requests
 - pip3 install os
 - pip3 intsall base64
script:
 - cd flaskapp
 - ./st.sh
